### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "HarpreetWP@gmail.com",
  "password": "Pass@123"
}


### Find a particular user with given ID

GET http://localhost:3000/auth/4

### Find a particular user with given Email

GET http://localhost:3000/auth/?email=HarpreetWP@gmail.com

### Delete a method with given ID

DELETE  http://localhost:3000/auth/2

###Update a user
PATCH http://localhost:3000/auth/99
Content-Type: application/json

{
  "password" : "Pass@000"
}
