### Create a report

POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "ford",
  "model": "figo",
  "year": 2012,
  "milege": 35000,
  "lng": 0,
  "lat": 1,
  "price": 610000
}